name: Newman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-newman:
    runs-on: ubuntu-latest

    env:
      API_USER: ${{ secrets.API_USER }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}



    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v7

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      # 3. Instalar Newman
      - name: Install Newman
        run: npm install -g newman

      # 4. Instalar Newman Reporters
      - name: Install Newman Reporters
        run: npm install -g newman-reporter-allurereport

      # 5. Instalar Allure
      - name: Install Allure
        run: npm install -g allure-commandline

      # 6. Ejecutar colección con reporter de Allure
      - name: Run Postman Collection
        run: |
          mkdir -p allure-results
          newman run Todoly.postman_collection.json \
            -e Todoly_UAT.postman_environment.json \
            --env-var "userName=$API_USER" \
            --env-var "password=$API_PASSWORD" \
            -r cli,allurereport \
            --reporter-allurereport-export allure-results

      # 7. Generar reporte de Allure
      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results -o allure-report --clean

      # 8. Guardar reportes como artefactos
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: allure-report/